### ISSUE TITLE
If package is added via simple import - each full reimport breaks defualt addressables groups 

### ISSUE THREAD

**Issue by studentutu** [Haruma-K/EZAddresser#3]
If package is added via simple import - each full reimport breaks default addressable groups.

Tested on 4 different machines. 2 different projects

All data is valid, but something breaks the default addressable package.

To Reproduce :
1) Import as a simple scripts folder somewhere under your project
2) Work on your targets,groups, setup the EZAddressable
3) Commit your changes ( also commit EZAddressable data!)
4) Reimport project

Expected result : 
 Project loads and all of the groups are intact

Actual Result : 
 Project is loaded, EZAddressables throws the exception of not finding the right package data
 Whole Addressable Assets group is broken.

To Fix it I need to manually delete whole Addressable  folder (in root) and re-sign the EZAddressable packed data once again.
That fixes all of the references and everything works again. All Test pass.

**Comment by Haruma-K** [comment]
@studentutu 

Thank you for the bug report.

I have released a fix in the following version.
Make sure the error does not reproduce.

https://github.com/Haruma-K/EZAddresser/releases/tag/0.2.4
